
services:
  mc-modpack-installer:



    user: "0:0"
    build:
      context: .
      dockerfile: Dockerfile.modinstaller
    volumes:
      - ./modpack:/modpack
      - ./data:/data
      - ./scripts:/scripts
    environment:
      MODRINTH_URL: ${MODRINTH_URL:-https://cdn.modrinth.com/data/Jkb29YJU/versions/3EqJgqlj/COBBLEVERSE%201.5.6.mrpack}
      SERVER_WORLDNAME: ${SERVER_WORLDNAME:-Zoo}
    entrypoint: ["/bin/sh", "/scripts/install-modpack.sh"]


  mc:




    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "FABRIC"
      VERSION: "1.21.1"
      FABRIC_LOADER_VERSION: "latest"
      FABRIC_LAUNCHER_VERSION: "latest"
      MEMORY: "4G"
      SERVER_WORLDNAME: ${SERVER_WORLDNAME:-Zoo}
      LEVEL: ${SERVER_WORLDNAME:-Zoo}
      ENABLE_WHITELIST: "false"
      DEBUG: ${DEBUG:-False}
      SERVER_NAME: ${SERVER_NAME_-Cobbleverse}
      ICON: ${SERVER_ICON:-}
      ALLOW_FLIGHT: ${ALLOW_FLIGHT:-False}
      SPAWN_MONSTERS: ${SPAWN_MONSTERS:-False}


    volumes:
      - ./modpack:/modpack
      - ./data:/data
      - ./worlds:/data/worlds
      - ./scripts/wait-for-modpack.sh:/wait-for-modpack.sh
    entrypoint: ["/bin/sh", "/wait-for-modpack.sh"]
    command: []
    ports:
      - "25565:25565"
    depends_on:
      - mc-modpack-installer
    restart: unless-stopped

networks:
  default:
    name: npm_default
    external: true




























